name: Update Go Projects Rooks

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9].[0-9]+.*'

jobs:
  update_projects:
    runs-on: ubuntu-latest
    env:
      GO_ROOK_VERSION:  ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout management repo
        uses: actions/checkout@v3
        with:
          repository: Rookout/management
          token: ${{ secrets.SONARIO_GITHUB_TOKEN }}
          path: management
      - name: Checkout data-pipelines repo
        uses: actions/checkout@v3
        with:
          repository: Rookout/data-pipelines
          token: ${{ secrets.SONARIO_GITHUB_TOKEN }}
          path: data-pipelines
      - name: Update management
        working-directory: ./management
        run: |
          go get -u github.com/Rookout/GoSDK@${{env.GO_ROOK_VERSION}}
          git config --global user.email "sonario@rookout.com"
          git config --global user.name "sonariorobot"
          git remote -v
          git add -A
          git status
          git commit -m "Update GoSDK to: ${{env.GO_ROOK_VERSION}}"
          git push
      - name: Update data-pipelines
        working-directory: ./data-pipelines
        run: |
          go get -u github.com/Rookout/GoSDK@${{env.GO_ROOK_VERSION}}
          git config --global user.email "sonario@rookout.com"
          git config --global user.name "sonariorobot"
          git remote -v
          git add -A
          git status
          git commit -m "Update GoSDK to: ${{env.GO_ROOK_VERSION}}"
          git push
